# Generated by Django 5.0.1 on 2024-02-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('estado_pago', models.CharField(max_length=100)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendita.orden')),
            ],
        ),
    ]
