# Generated by Django 5.0.1 on 2024-02-26 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0004_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEducativo',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('archivo', models.FileField(upload_to='archivos_educativos/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tiendita.empleado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='Tiendita.categoria')),
                ('productos_relacionados', models.ManyToManyField(related_name='contenidos_relacionados', to='Tiendita.producto')),
            ],
        ),
    ]
