# Generated by Django 5.0.1 on 2024-02-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0005_contenidoeducativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContenidoEducativo',
        ),
    ]
