# Generated by Django 5.0.1 on 2024-03-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0007_membresia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
