# Generated by Django 5.0.1 on 2024-03-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0008_alter_transaccion_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Tiendita.producto'),
            preserve_default=False,
        ),
    ]
