# Generated by Django 5.0.1 on 2024-03-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0010_remove_orden_producto_orden_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='productos',
        ),
        migrations.AddField(
            model_name='orden',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tiendita.producto'),
            preserve_default=False,
        ),
    ]
