# Generated by Django 5.0.1 on 2024-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0013_transaccion_producto_alter_transaccion_monto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='producto',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
