# Generated by Django 5.0.1 on 2024-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0014_remove_transaccion_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
