# Generated by Django 5.0.1 on 2024-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0015_alter_transaccion_monto_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
