# Generated by Django 5.0.1 on 2024-04-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0016_alter_transaccion_monto_total'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.UniqueConstraint(fields=('orden',), name='unique_order_transaction'),
        ),
    ]
