# Generated by Django 5.0.1 on 2024-04-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0017_transaccion_unique_order_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], max_length=100),
        ),
    ]
