# Generated by Django 5.0.1 on 2024-04-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0018_alter_transaccion_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado_pago',
            field=models.CharField(max_length=100),
        ),
    ]
