# Generated by Django 5.0.1 on 2024-04-08 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0019_alter_transaccion_estado_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='estado_pago',
        ),
    ]
