# Generated by Django 5.0.1 on 2024-04-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0020_remove_transaccion_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
