# Generated by Django 5.0.1 on 2024-04-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tiendita', '0024_alter_servicio_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='estado_pago',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
